print("Welcome to Mad Libs!")
name = input("What is your name? ")
adj = input("Enter an adjective: ")
verb = input("Enter a verb: ")
place = input("Enter a place: ")
food = input("Enter a food: ")
vehicle = input("Enter a vehicle: ")
print(f"{name} is a very {adj} person to be around. They love to cook in {place}. Their favourite food is {food} which they eat in a {vehicle}.")